services:
  web:
    build:
      context: .
      dockerfile: ppfc.web/Dockerfile
    ports:
      - "9000:8080"
    depends_on:
      - api
      - gateway

  api:
    build:
      context: .
      dockerfile: ppfc.API/Dockerfile
    ports:
      - "9001:8080"

  gateway:
    build:
      context: .
      dockerfile: ppfc.APIGateway/Dockerfile
    ports:
      - "9002:8080"
